I forgot the CEGUI-files..
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	new file:   Cheese Leather 2D/Debug/datafiles/animations/GameMenu.anims
#	new file:   Cheese Leather 2D/Debug/datafiles/animations/example.anims
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Batang-18.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/DejaVuSans-10-NoScale.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/DejaVuSans-10.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/DejaVuSans-12-NoScale.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/DejaVuSans-12.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/DejaVuSans-14-NoScale.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/DejaVuSans-14.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/DejaVuSans.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/DejaVuSerif.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/FairChar-30.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/FetteClassicUNZFraktur.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Futhark Adapted.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/GreatVibes-16.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/GreatVibes-22.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/GreatVibes-Regular.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/IMFePIrm29P.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Junicode-13.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Junicode.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Jura-10.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Jura-13.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Jura-18.font
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Jura-DemiBold.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Jura-Light.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Jura-Medium.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Jura-Regular.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Klingon-pIqaD-HaSta.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Legal.txt
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/LicenseApache.txt
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/LicenseDejaVu.txt
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/LicenseGPL.txt
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/LicenseMIT.txt
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/LicenseSIL.txt
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/LicenseUbuntuFont.txt
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/RichStyle.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/Tnua-Libre.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/batang.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/fonts/mizufalp.ttf
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/AlfiskoSkin.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/AlfiskoSkin.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/Aliasing.jpg
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/BackgroundSampleBrowser.jpg
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/DriveIcons.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/DriveIcons.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/FairChar.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/FairChar.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/GameMenu.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/GameMenu.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/HUDDemo.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/HUDDemo.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/HUDDemoGameOver.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/OgreTray.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/OgreTrayImages.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/ReadMe.txt
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/SampleBrowser.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/SampleBrowser.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/SpaceBackground.jpg
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/TaharezLook.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/TaharezLook.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/Vanilla.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/WindowsLook.imageset
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/WindowsLook.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/logo.png
#	new file:   Cheese Leather 2D/Debug/datafiles/imagesets/vanilla.png
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/Console.wnd
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/Demo8.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/DragDropDemo.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/EffectsDemo.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/FontDemo.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/GameMenu.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/HUDDemoGameOver.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/HUDDemoIngame.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/SampleBrowser.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/SampleBrowserLoadScreen.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/TabControlDemo.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/TabPage.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/TabPage1.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/TabPage1.layout.orig
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/TabPage2.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/TextDemo.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/TreeDemoTaharez.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/VanillaConsole.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/layouts/VanillaWindows.layout
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/AlfiskoSkin.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/GameMenu.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/Generic.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/HUDDemo.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/Inherited.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/InventoryComponents.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/OgreTray.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/SampleBrowser.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/TaharezLook.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/Vanilla.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/VanillaCommonDialogs.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/looknfeel/WindowsLook.looknfeel
#	new file:   Cheese Leather 2D/Debug/datafiles/lua_scripts/demo8.lua
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/AlfiskoSkin.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/GameMenu.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/Generic.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/HUDDemo.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/OgreTray.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/SampleBrowser.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/TaharezLook.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/TaharezLook.scheme.orig
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/VanillaCommonDialogs.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/VanillaCommonDialogs.scheme.orig
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/VanillaSkin.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/schemes/WindowsLook.scheme
#	new file:   Cheese Leather 2D/Debug/datafiles/xml_schemas/Animation.xsd
#	new file:   Cheese Leather 2D/Debug/datafiles/xml_schemas/CEGUIConfig.xsd
#	new file:   Cheese Leather 2D/Debug/datafiles/xml_schemas/Falagard.xsd
#	new file:   Cheese Leather 2D/Debug/datafiles/xml_schemas/Font.xsd
#	new file:   Cheese Leather 2D/Debug/datafiles/xml_schemas/GUILayout.xsd
#	new file:   Cheese Leather 2D/Debug/datafiles/xml_schemas/GUIScheme.xsd
#	new file:   Cheese Leather 2D/Debug/datafiles/xml_schemas/Imageset.xsd
#	new file:   Cheese Leather 2D/Debug/datafiles/xml_schemas/Samples.xsd
#	new file:   Cheese Leather 2D/datafiles/Copy this folder to Debug and Release.txt
#	new file:   Cheese Leather 2D/datafiles/animations/GameMenu.anims
#	new file:   Cheese Leather 2D/datafiles/animations/example.anims
#	new file:   Cheese Leather 2D/datafiles/fonts/Batang-18.font
#	new file:   Cheese Leather 2D/datafiles/fonts/DejaVuSans-10-NoScale.font
#	new file:   Cheese Leather 2D/datafiles/fonts/DejaVuSans-10.font
#	new file:   Cheese Leather 2D/datafiles/fonts/DejaVuSans-12-NoScale.font
#	new file:   Cheese Leather 2D/datafiles/fonts/DejaVuSans-12.font
#	new file:   Cheese Leather 2D/datafiles/fonts/DejaVuSans-14-NoScale.font
#	new file:   Cheese Leather 2D/datafiles/fonts/DejaVuSans-14.font
#	new file:   Cheese Leather 2D/datafiles/fonts/DejaVuSans.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/DejaVuSerif.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/FairChar-30.font
#	new file:   Cheese Leather 2D/datafiles/fonts/FetteClassicUNZFraktur.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/Futhark Adapted.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/GreatVibes-16.font
#	new file:   Cheese Leather 2D/datafiles/fonts/GreatVibes-22.font
#	new file:   Cheese Leather 2D/datafiles/fonts/GreatVibes-Regular.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/IMFePIrm29P.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/Junicode-13.font
#	new file:   Cheese Leather 2D/datafiles/fonts/Junicode.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/Jura-10.font
#	new file:   Cheese Leather 2D/datafiles/fonts/Jura-13.font
#	new file:   Cheese Leather 2D/datafiles/fonts/Jura-18.font
#	new file:   Cheese Leather 2D/datafiles/fonts/Jura-DemiBold.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/Jura-Light.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/Jura-Medium.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/Jura-Regular.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/Klingon-pIqaD-HaSta.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/Legal.txt
#	new file:   Cheese Leather 2D/datafiles/fonts/LicenseApache.txt
#	new file:   Cheese Leather 2D/datafiles/fonts/LicenseDejaVu.txt
#	new file:   Cheese Leather 2D/datafiles/fonts/LicenseGPL.txt
#	new file:   Cheese Leather 2D/datafiles/fonts/LicenseMIT.txt
#	new file:   Cheese Leather 2D/datafiles/fonts/LicenseSIL.txt
#	new file:   Cheese Leather 2D/datafiles/fonts/LicenseUbuntuFont.txt
#	new file:   Cheese Leather 2D/datafiles/fonts/RichStyle.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/Tnua-Libre.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/batang.ttf
#	new file:   Cheese Leather 2D/datafiles/fonts/mizufalp.ttf
#	new file:   Cheese Leather 2D/datafiles/imagesets/AlfiskoSkin.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/AlfiskoSkin.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/Aliasing.jpg
#	new file:   Cheese Leather 2D/datafiles/imagesets/BackgroundSampleBrowser.jpg
#	new file:   Cheese Leather 2D/datafiles/imagesets/DriveIcons.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/DriveIcons.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/FairChar.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/FairChar.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/GameMenu.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/GameMenu.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/HUDDemo.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/HUDDemo.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/HUDDemoGameOver.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/OgreTray.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/OgreTrayImages.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/ReadMe.txt
#	new file:   Cheese Leather 2D/datafiles/imagesets/SampleBrowser.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/SampleBrowser.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/SpaceBackground.jpg
#	new file:   Cheese Leather 2D/datafiles/imagesets/TaharezLook.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/TaharezLook.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/Vanilla.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/WindowsLook.imageset
#	new file:   Cheese Leather 2D/datafiles/imagesets/WindowsLook.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/logo.png
#	new file:   Cheese Leather 2D/datafiles/imagesets/vanilla.png
#	new file:   Cheese Leather 2D/datafiles/layouts/Console.wnd
#	new file:   Cheese Leather 2D/datafiles/layouts/Demo8.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/DragDropDemo.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/EffectsDemo.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/FontDemo.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/GameMenu.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/HUDDemoGameOver.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/HUDDemoIngame.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/SampleBrowser.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/SampleBrowserLoadScreen.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/TabControlDemo.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/TabPage.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/TabPage1.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/TabPage1.layout.orig
#	new file:   Cheese Leather 2D/datafiles/layouts/TabPage2.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/TextDemo.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/TreeDemoTaharez.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/VanillaConsole.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/VanillaWindows.layout
#	new file:   Cheese Leather 2D/datafiles/layouts/test.layout
#	new file:   Cheese Leather 2D/datafiles/looknfeel/AlfiskoSkin.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/GameMenu.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/Generic.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/HUDDemo.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/Inherited.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/InventoryComponents.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/OgreTray.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/SampleBrowser.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/TaharezLook.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/Vanilla.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/VanillaCommonDialogs.looknfeel
#	new file:   Cheese Leather 2D/datafiles/looknfeel/WindowsLook.looknfeel
#	new file:   Cheese Leather 2D/datafiles/lua_scripts/demo8.lua
#	new file:   Cheese Leather 2D/datafiles/schemes/AlfiskoSkin.scheme
#	new file:   Cheese Leather 2D/datafiles/schemes/GameMenu.scheme
#	new file:   Cheese Leather 2D/datafiles/schemes/Generic.scheme
#	new file:   Cheese Leather 2D/datafiles/schemes/HUDDemo.scheme
#	new file:   Cheese Leather 2D/datafiles/schemes/OgreTray.scheme
#	new file:   Cheese Leather 2D/datafiles/schemes/SampleBrowser.scheme
#	new file:   Cheese Leather 2D/datafiles/schemes/TaharezLook.scheme
#	new file:   Cheese Leather 2D/datafiles/schemes/TaharezLook.scheme.orig
#	new file:   Cheese Leather 2D/datafiles/schemes/VanillaCommonDialogs.scheme
#	new file:   Cheese Leather 2D/datafiles/schemes/VanillaCommonDialogs.scheme.orig
#	new file:   Cheese Leather 2D/datafiles/schemes/VanillaSkin.scheme
#	new file:   Cheese Leather 2D/datafiles/schemes/WindowsLook.scheme
#	new file:   Cheese Leather 2D/datafiles/xml_schemas/Animation.xsd
#	new file:   Cheese Leather 2D/datafiles/xml_schemas/CEGUIConfig.xsd
#	new file:   Cheese Leather 2D/datafiles/xml_schemas/Falagard.xsd
#	new file:   Cheese Leather 2D/datafiles/xml_schemas/Font.xsd
#	new file:   Cheese Leather 2D/datafiles/xml_schemas/GUILayout.xsd
#	new file:   Cheese Leather 2D/datafiles/xml_schemas/GUIScheme.xsd
#	new file:   Cheese Leather 2D/datafiles/xml_schemas/Imageset.xsd
#	new file:   Cheese Leather 2D/datafiles/xml_schemas/Samples.xsd
#
